In [1]:
# 资产负债和数据完整实行周末完成
# 现已跑通简单的svm以未来Dretnd为预测目标的模型
import pandas as pd
import numpy as np
df=pd.read_csv("/home/xinyang/Kaggle/TRD/TRD_Dalyr1.csv",encoding='utf-16',sep='\t')
df.head()

,Stkcd,Trddt,Opnprc,Hiprc,Loprc,Clsprc,Dnshrtrd,Dnvaltrd,Dsmvosd,Dsmvtll,Dretwd,Dretnd,Adjprcwd,Adjprcnd,Markettype,Capchgdt,Trdsta,Dretnd_next
0,600235,5/4/2009,5.18,5.36,5.13,5.33,12101026,63630177.0,1403922.00,1403922.0,0.025000,0.025000,10.735694,10.013117,1,4/28/2009,1,0.027668
1,600235,4/30/2009,5.06,5.27,4.98,5.20,10568865,54270004.0,1369680.00,1369680.0,0.027668,0.027668,10.473848,9.768894,1,4/28/2009,1,0.030550
2,600235,4/29/2009,4.93,5.18,4.90,5.06,12534860,63508083.0,1332804.00,1332804.0,0.030550,0.030550,10.191860,9.505886,1,4/28/2009,1,0.002041
3,600235,4/28/2009,4.89,4.93,4.71,4.91,6911499,33480382.0,1293294.00,1293294.0,0.002041,0.002041,9.889729,9.224091,1,4/28/2009,1,0.020833
4,600235,4/27/2009,4.83,4.96,4.71,4.90,8036147,38894288.0,720043.73,1290660.0,0.020833,0.020833,9.869587,9.205304,1,4/28/2008,1,0.012658

In [2]:
from sklearn import svm
from sklearn import preprocessing
y=df["Dretnd_next"]
lab_enc = preprocessing.LabelEncoder()
y = lab_enc.fit_transform(y)
X= df.drop(["Dretnd_next","Dretnd","Trddt","Capchgdt"],axis=1)
clf = svm.SVC(gamma='scale')
clf.fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)